import React from 'react';
import { motion } from 'framer-motion';
import { 
  Heart, FileText, Salad, Download, Activity, 
  CheckCircle, AlertTriangle, AlertCircle, Calendar
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import Navbar from '@/components/Navbar';
import { useAuth } from '@/contexts/AuthContext';
import { usePatientData } from '@/contexts/PatientDataContext';

const PatientDashboard: React.FC = () => {
  const { user } = useAuth();
  const { getLatestReport, getPatientReports, isLoading } = usePatientData();
  
  const latestReport = user ? getLatestReport(user.email) : null;
  const allReports = user ? getPatientReports(user.email) : [];

  const getRiskColor = (level: 'low' | 'medium' | 'high') => {
    switch (level) {
      case 'high': return { text: 'text-destructive', bg: 'bg-destructive', gradient: 'from-destructive to-destructive/70' };
      case 'medium': return { text: 'text-warning', bg: 'bg-warning', gradient: 'from-warning to-warning/70' };
      default: return { text: 'text-success', bg: 'bg-success', gradient: 'from-success to-success/70' };
    }
  };

  const getRiskIcon = (level: 'low' | 'medium' | 'high') => {
    switch (level) {
      case 'high': return <AlertCircle className="h-6 w-6" />;
      case 'medium': return <AlertTriangle className="h-6 w-6" />;
      default: return <CheckCircle className="h-6 w-6" />;
    }
  };

  const handleDownloadPDF = () => {
    const content = latestReport ? `
CardioCare Medical Report
========================

Patient: ${latestReport.patientName}
Date: ${new Date(latestReport.publishedAt!).toLocaleDateString()}

Risk Score: ${latestReport.riskScore}%
Risk Level: ${latestReport.riskLevel.toUpperCase()}

Clinical Data:
- Age: ${latestReport.clinicalData.age}
- Blood Pressure: ${latestReport.clinicalData.trestbps} mmHg
- Cholesterol: ${latestReport.clinicalData.chol} mg/dl
- Max Heart Rate: ${latestReport.clinicalData.thalach}

Diet Plan:
${latestReport.dietPlan}

Recommendations:
${latestReport.recommendations.map(r => `- ${r}`).join('\n')}

This report is generated by CardioCare AI Health Platform.
    ` : 'No report available';

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'CardioCare_Medical_Report.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="flex items-center justify-center pt-32">
          <div className="h-8 w-8 border-4 border-primary/30 border-t-primary rounded-full animate-spin" />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="pt-20 pb-10 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground mb-2">
              Welcome, {user?.name}
            </h1>
            <p className="text-muted-foreground">Your personalized heart health dashboard</p>
          </div>

          {latestReport ? (
            <div className="grid lg:grid-cols-3 gap-6">
              {/* Health Score Card */}
              <Card className="lg:col-span-2">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Activity className="h-5 w-5 text-primary" />
                    Latest Heart Health Report
                  </CardTitle>
                  <CardDescription>
                    Published on {new Date(latestReport.publishedAt!).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric'
                    })}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col md:flex-row items-center gap-8">
                    {/* Circular Gauge */}
                    <div className="relative">
                      <svg className="w-48 h-48 transform -rotate-90">
                        <circle
                          cx="96"
                          cy="96"
                          r="80"
                          stroke="currentColor"
                          strokeWidth="12"
                          fill="none"
                          className="text-muted"
                        />
                        <motion.circle
                          cx="96"
                          cy="96"
                          r="80"
                          stroke="currentColor"
                          strokeWidth="12"
                          fill="none"
                          strokeLinecap="round"
                          className={getRiskColor(latestReport.riskLevel).text}
                          initial={{ strokeDasharray: "0 502" }}
                          animate={{ strokeDasharray: `${(latestReport.riskScore / 100) * 502} 502` }}
                          transition={{ duration: 1.5, ease: "easeOut" }}
                        />
                      </svg>
                      <div className="absolute inset-0 flex flex-col items-center justify-center">
                        <span className={`text-4xl font-bold ${getRiskColor(latestReport.riskLevel).text}`}>
                          {latestReport.riskScore}%
                        </span>
                        <span className="text-sm text-muted-foreground">Risk Score</span>
                      </div>
                    </div>

                    {/* Stats */}
                    <div className="flex-1 space-y-4">
                      <div className={`p-4 rounded-xl ${getRiskColor(latestReport.riskLevel).bg}/10`}>
                        <div className="flex items-center gap-3">
                          <div className={`p-2 rounded-lg ${getRiskColor(latestReport.riskLevel).bg} text-white`}>
                            {getRiskIcon(latestReport.riskLevel)}
                          </div>
                          <div>
                            <p className="text-sm text-muted-foreground">Risk Level</p>
                            <p className={`text-xl font-bold capitalize ${getRiskColor(latestReport.riskLevel).text}`}>
                              {latestReport.riskLevel} Risk
                            </p>
                          </div>
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div className="p-4 rounded-xl bg-muted">
                          <p className="text-sm text-muted-foreground">Blood Pressure</p>
                          <p className="text-xl font-semibold">{latestReport.clinicalData.trestbps} mmHg</p>
                        </div>
                        <div className="p-4 rounded-xl bg-muted">
                          <p className="text-sm text-muted-foreground">Cholesterol</p>
                          <p className="text-xl font-semibold">{latestReport.clinicalData.chol} mg/dl</p>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Recommendations */}
                  <div className="mt-8">
                    <h4 className="font-semibold text-foreground mb-3">Doctor's Recommendations</h4>
                    <ul className="space-y-2">
                      {latestReport.recommendations.slice(0, 4).map((rec, i) => (
                        <motion.li
                          key={i}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.1 }}
                          className="flex items-start gap-2"
                        >
                          <CheckCircle className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                          <span className="text-sm text-muted-foreground">{rec}</span>
                        </motion.li>
                      ))}
                    </ul>
                  </div>
                </CardContent>
              </Card>

              {/* Diet Plan & Download */}
              <div className="space-y-6">
                {/* Diet Plan */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Salad className="h-5 w-5 text-secondary" />
                      AI Diet Plan
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className={`p-4 rounded-xl bg-gradient-to-br ${getRiskColor(latestReport.riskLevel).gradient} text-white mb-4`}>
                      <p className="font-semibold mb-1">
                        {latestReport.riskLevel === 'high' ? 'DASH Diet - Low Sodium' :
                         latestReport.riskLevel === 'medium' ? 'Mediterranean Modified' :
                         'Balanced Maintenance'}
                      </p>
                      <p className="text-sm text-white/80">Personalized for your health profile</p>
                    </div>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      {latestReport.dietPlan}
                    </p>
                  </CardContent>
                </Card>

                {/* Download */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <FileText className="h-5 w-5 text-primary" />
                      Medical Report
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground mb-4">
                      Download your complete medical report with all clinical data and recommendations.
                    </p>
                    <Button
                      variant="hero"
                      className="w-full"
                      onClick={handleDownloadPDF}
                    >
                      <Download className="h-4 w-4" />
                      Download Report
                    </Button>
                  </CardContent>
                </Card>

                {/* History */}
                {allReports.length > 1 && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Calendar className="h-5 w-5 text-primary" />
                        Report History
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-3">
                        {allReports.slice(0, 3).map((report) => (
                          <div
                            key={report.id}
                            className="flex items-center justify-between p-3 rounded-lg bg-muted"
                          >
                            <div>
                              <p className="text-sm font-medium">
                                {new Date(report.publishedAt!).toLocaleDateString()}
                              </p>
                              <p className="text-xs text-muted-foreground capitalize">
                                {report.riskLevel} risk
                              </p>
                            </div>
                            <div className={`font-bold ${getRiskColor(report.riskLevel).text}`}>
                              {report.riskScore}%
                            </div>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                )}
              </div>
            </div>
          ) : (
            /* No Reports State */
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <Card className="max-w-2xl mx-auto">
                <CardContent className="py-16 text-center">
                  <div className="h-20 w-20 rounded-full bg-accent flex items-center justify-center mx-auto mb-6">
                    <Heart className="h-10 w-10 text-primary animate-heartbeat" />
                  </div>
                  <h2 className="text-2xl font-bold text-foreground mb-3">
                    No Reports Yet
                  </h2>
                  <p className="text-muted-foreground max-w-md mx-auto mb-6">
                    Your healthcare provider hasn't published any heart health reports yet. 
                    Once your clinical data is analyzed, you'll see your personalized health 
                    insights here.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <CheckCircle className="h-4 w-4 text-success" />
                      AI-powered analysis
                    </div>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <CheckCircle className="h-4 w-4 text-success" />
                      Personalized diet plans
                    </div>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <CheckCircle className="h-4 w-4 text-success" />
                      Downloadable reports
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}
        </div>
      </main>
    </div>
  );
};

export default PatientDashboard;
